---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: recipes.dope.mayadata.io
spec:
  group: dope.mayadata.io
  names:
    kind: Recipe
    listKind: RecipeList
    plural: recipes
    shortNames:
    - rcp
    singular: recipe
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Age
    type: date
    description: Age of this Recipe
    JSONPath: .metadata.creationTimestamp
  - name: TimeTaken
    type: string
    description: Time taken to execute this Recipe
    JSONPath: .status.executionTime.readableValue
  - name: Status
    type: string
    description: Current phase of this Recipe
    JSONPath: .status.phase
  - name: Reason
    type: string
    description: Description of this phase
    JSONPath: .status.reason
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: https.dope.mayadata.io
spec:
  group: dope.mayadata.io
  names:
    kind: HTTP
    listKind: HTTPList
    plural: https
    shortNames:
    - http
    singular: http
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: commands.dope.mayadata.io
spec:
  group: dope.mayadata.io
  names:
    kind: Command
    listKind: CommandList
    plural: commands
    shortNames:
    - cmds
    singular: command
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
